version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://tkmremi:547a0283Re&@db:5432/syncstart
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: syncstart
      POSTGRES_USER: tkmremi
      POSTGRES_PASSWORD: 547a0283Re&
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  prisma-migrate:
    image: node:latest
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npx prisma migrate deploy
    environment:
      DATABASE_URL: postgresql://tkmremi:547a0283Re&@db:5432/syncstart
    depends_on:
      - db

volumes:
  postgres_data: